project/mainapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
    path('best9/', views.best9, name='best9'),
    path('cafemap/', views.cafemap, name='cafemap'),
    path('brandmenu/', views.brandmenu, name='brandmenu'),
    path('post/', views.post, name='post'),
    path('post/write/', views.write, name='write'),
    path('view/', views.view, name='view'),
    path('islike/', views.islike, name='islike'),
    path('notlike/', views.notlike, name='notlike'),
    path('update_cnt/', views.update_cnt, name='update_cnt'),
    path('mypage/', views.mypage, name='mypage'),
    path('userpost/', views.userpost, name='userpost'),
    path('remove/', views.remove, name='remove'),
    path('update/', views.update, name='update'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls')),
    path('usersapp/', include('usersapp.urls')),

]

project/usersapp/urls.py
from django.urls import path
from .import views


app_name="usersapp"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgot/', views.forgot, name='forgot'),
    path('pwreset/',views.pwreset, name='pwreset'),
]

project/usersapp/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    useremail = models.EmailField(max_length=30, primary_key=True, verbose_name="이메일(아이디)")
    username = models.CharField(max_length=12, verbose_name="사용자 이름")
    password = models.CharField(max_length=12, verbose_name="비밀 번호")

project/usersapp/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render, redirect

# Create your views here.
from usersapp.models import Users


def login(request):
    context = {}

    if 'next' not in request.session:
        request.session['next']=request.GET.get('next',None)


    if request.method == 'POST': #POST방식으로 요청받으면, useremail에는 POST방식으로 받아온 input name이 email인 value값을 가져오고,
        # 그 값이 없으면 오류가 아니라 None으로 처리한다.(하지만 input 방식이 required이기 때문에 입력 받은 값이 없을 수는 없다.)
        useremail = request.POST.get('email', None)
        password = request.POST.get('password', None)
        try:
            user = Users.objects.get(useremail=useremail)
        #Users 클래스에 저장된 useremail 객체를 가져오는데, 그 useremail은 위에서 정의한 useremail이다.
        #Users 클래스의 모든 객체를 가져오려면 Users.objects.all()
        except Users.DoesNotExist:
            context['error']='아이디 또는 비밀번호가 일치하지 않습니다.'
            return render(request,'login.html',context)
        # 예외처리문 : get한 useremail이 Users 클래스에 저장된 객체가 아니라면, error 메세지를 login.html 파일과 함께 랜더링한다.(딕셔너리형태)
        else:
            user_name=user.username
            if check_password(password, user.password):
                #입력한 비밀번호와 db에 등록된 user.password를 비교해서 같다면,
                request.session['email']=useremail
                request.session['user'] = user_name
                context['next']=request.session['next']
                del request.session['next']

                if 'error' in request.session:
                    del request.session['error']

                #session에 user키의 value를 위에서 정의한 user_name으로 저장한다.
                return redirect(context['next'])
            #로그인에 성공했으면 /mainapp/home/으로 redirect
            else:
                context['error']='아이디 또는 비밀번호가 일치하지 않습니다.'
                #먄약 입력한 비밀번호와 db에 등록된 password가 다르면 error메세지와 함께 다시 login.html을 랜더링한다.
                return render(request, 'login.html', context)
    else:
        return render(request, 'login.html', context)
    #get방식일때는 login.html을 랜더링한다. 맨 처음 로그인 페이지에 접근했을 때 보여지는 화면.



def register(request):
    if request.method =='GET':
        return render(request, 'register.html')
    #get방식이면 register.html을 렌더링한다. 처음 보여지는 등록 화면.
    elif request.method == 'POST':
        useremail = request.POST.get('email', None)
        #POST방식으로 받아온 input name이 email인 value를 useremail에 저장한다.
        username = request.POST.get('name', None)
        #POST방식으로 받아온 input name이 name인 value를 username에 저장한다.
        password = request.POST.get('password', None)
        # POST방식으로 받아온 input name이 password인 value를 password에 저장한다.
        re_password = request.POST.get('re-password', None)
        res_data={}
        try:
            user=Users.objects.get(useremail=useremail)

        except Users.DoesNotExist:
            if password != re_password:
                res_data['error'] = '비밀번호가 다릅니다.'
                return render(request, 'register.html', res_data)
            else:
                users = Users(
                    useremail=useremail,
                    username=username,
                    password=make_password(password)
                )
                users.save()
                return render(request, 'login.html')

        else:
            res_data['error']="이미 존재하는 이메일 입니다."
            return render(request, 'register.html', res_data)


def forgot(request):
    if request.method == "POST":
        useremail=request.POST.get("email")
        try:
            user = Users.objects.get(useremail=useremail)
        except Users.DoesNotExist:
            context = {'error': '없는 이메일 주소입니다.'}
            return render(request,'forgot.html',context)
        else:
            request.session['email']=useremail
            return redirect('/usersapp/pwreset/?email='+useremail)
    else:
        return render(request, 'forgot.html')

def pwreset(request):
    if request.method == "POST":
        password=request.POST.get("password")
        re_password=request.POST.get("re-password")
        e = request.GET.get('email', "NotFound")
        if password != re_password:
            return render(request,'pwreset.html',context={"error":"비밀번호가 일치하지 않습니다.",'email':e})
        else:
            if e == "NotFound": return render(request,'/usersapp/forgot/',{'error':"변경할 이메일을 입력해 주세요."})
            user=Users.objects.get(useremail=e)
            user.password=make_password(password)
            user.save()
            return redirect("usersapp:login")
    else:
        e=request.GET.get('email',"NotFound")
        if e == "NotFound": return render(request, 'forgot.html', {'error': "변경할 이메일을 입력해 주세요."})
        return render(request, 'pwreset.html',{'email':request.GET['email']})

project/usersapp/templates/forgot.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/my-login.css">
</head>
<body class="my-login-page">
	{% if error%}
		<script>
			alert("{{error}}");
		</script>
	{% endif %}
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<a href="{% url 'home' %}"><img src="/static/img/logo_login.png"></a>
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Forgot Password</h4>
							<form method="POST" action="{% url 'usersapp:forgot'%}">
								{% csrf_token %}
								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
									<div class="form-text text-muted">
										Don't forget again!!
									</div>
								</div>

								<div class="form-group no-margin">
									<a href="#" style="text-decoration:none;"><button type="submit" class="btn btn-primary btn-block" style="background-color:#4d3319; border-color:#4d3319;  cursor:pointer;">
										Reset Password
									</button></a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright © Cafe Olleh 2020
					</div>
				</div>
			</div>
		</div>
	</section>
</body>
</html>

project/usersapp/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/my-login.css">
</head>
<body class="my-login-page">
	{% if error %}
		<script>
			alert("{{error}}");
		</script>
	{% endif %}

	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<a href="{% url 'home' %}"><img src="/static/img/logo_login.png"></a>
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Login</h4>
							<form method="POST" action="{% url 'usersapp:login'%}?next={{next}}">
								<!--server에게 /usersapp/login/페이지를 POST 방식으로 보내겠다.
								근데 post 방식인 경우 보안 목적으로 csrf를 꼭 써줘야한다.-->
								{% csrf_token %}
								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
								</div>

								<div class="form-group">
									<label for="password">Password
										<a href="{% url 'usersapp:forgot' %}" class="float-right" style="color:#4d3319;">
											Forgot Password?
										</a>
									</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								</div>



								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block" style="background-color:#4d3319; border-color:#4d3319; margin-top:20px; cursor:pointer;">
										Login
									</button>
								</div>
								<div class="margin-top20 text-center">
									Don't have an account? <a href="{% url 'usersapp:register' %}" style="color:#4d3319;">Create One</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright © Cafe Olleh 2020
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="/static/js/jquery.min.js"></script>
	<script src="/static/bootstrap/js/bootstrap.min.js"></script>
	<script src="/static/js/my-login.js"></script>
</body>
</html>

project/usersapp/templates/pwreset.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/my-login.css">
</head>
<body class="my-login-page">
	{% if error %}
		<script>
			alert("{{error}}");
			location.href="{% url 'usersapp:pwreset'%}?email="+"{{email}}";
		</script>
	{% endif%}
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<a href="{% url 'home' %}"><img src="/static/img/logo_login.png"></a>
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Reset Password</h4>
							<form method="POST" action="{% url 'usersapp:pwreset'%}?email={{email}}">
								{% csrf_token %}
								<div class="form-group">
									<label for="new-password">New Password</label>
									<input id="new-password" type="password" class="form-control" name="password" required autofocus data-eye>

									<label for="re-password">Re Password</label>
									<input id="re-password" type="password" class="form-control" name="re-password" required autofocus data-eye>
									<div class="form-text text-muted">
										Make sure your password is strong and easy to remember
									</div>
								</div>
								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block" style="background-color:#4d3319; border-color:#4d3319; cursor:pointer;">
										Reset Password
									</button>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright © Cafe Olleh 2020
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="js/jquery.min.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="js/my-login.js"></script>
</body>
</html>

project/usersapp/templates/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/my-login.css">
</head>
<body class="my-login-page">

	{% if error %}
		<script>
			alert("{{error}}");
		</script>
	{% endif %}

	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<a href="{% url 'home' %}"><img src="/static/img/logo_login.png"></a>
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Register</h4>
							<form method="POST" action="{% url 'usersapp:register'%}">
								<!--server에게 /usersapp/register/페이지를 POST 방식으로 보내겠다.
								근데 post 방식인 경우 보안 목적으로 csrf를 꼭 써줘야한다.-->
							 	 {% csrf_token %}
								<div class="form-group">
									<label for="name">Name</label>
									<input id="name" type="text" class="form-control" name="name" required autofocus>
								</div>

								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" required>
								</div>

								<div class="form-group">
									<label for="password">Password</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								</div>

								<div class="form-group">
									<label for="re-password">re-Password</label>
									<input id="re-password" type="password" class="form-control" name="re-password" required data-eye>
								</div>

								<div class="form-group">
									<label>
										<input type="checkbox" name="aggree" value="1" required> I agree to the Terms and Conditions
									</label>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block" style="background-color:#4d3319; border-color:#4d3319; cursor:pointer;">
										Register
									</button>
									<!--Register를 누르면 상단에 입력한 내용을 submit-->
								</div>
								<div class="margin-top20 text-center">
									Already have an account? <a href="{% url 'usersapp:login' %}" style="color:#4d3319;">Login</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; Cafe Olleh 2020
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="js/jquery.min.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="js/my-login.js"></script>
</body>
</html>