project/mainapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
    path('best9/', views.best9, name='best9'),
    path('cafemap/', views.cafemap, name='cafemap'),
    path('brandmenu/', views.brandmenu, name='brandmenu'),
    path('post/', views.post, name='post'),
    path('post/write/', views.write, name='write'),
    path('view/', views.view, name='view'),
    path('islike/', views.islike, name='islike'),
    path('notlike/', views.notlike, name='notlike'),
    path('update_cnt/', views.update_cnt, name='update_cnt'),
    path('mypage/', views.mypage, name='mypage'),
    path('userpost/', views.userpost, name='userpost'),
    path('remove/', views.remove, name='remove'),
    path('update/', views.update, name='update'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls')),
    path('usersapp/', include('usersapp.urls')),

]

project/usersapp/urls.py
from django.urls import path
from .import views


app_name="usersapp"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgot/', views.forgot, name='forgot'),
    path('pwreset/',views.pwreset, name='pwreset'),
]

project/mainapp/models.py
from django.db import models
from usersapp.models import Users

# Create your models here

class Product(models.Model):
    id=models.IntegerField(primary_key=True)
    products=models.CharField(max_length=20)

class Product_Bybrand(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE,primary_key=True)
    Starbucks=models.CharField(max_length=30, null=True)
    Twosome=models.CharField(max_length=30, null=True)
    TomandToms=models.CharField(max_length=30, null=True)
    Ediya=models.CharField(max_length=30, null=True)
    Mega=models.CharField(max_length=30, null=True)
    Hollys=models.CharField(max_length=30, null=True)
    Coffeebean=models.CharField(max_length=30, null=True)
    Coffeebay=models.CharField(max_length=30, null=True)
    Angelinus=models.CharField(max_length=30, null=True)
    Pascucci=models.CharField(max_length=30, null=True)

class Price_Bybrand(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE,primary_key=True)
    Starbucks=models.IntegerField(null=True)
    Twosome=models.IntegerField(null=True)
    TomandToms=models.IntegerField(null=True)
    Ediya=models.IntegerField(null=True)
    Mega=models.IntegerField(null=True)
    Hollys=models.IntegerField(null=True)
    Coffeebean=models.IntegerField(null=True)
    Coffeebay=models.IntegerField(null=True)
    Angelinus=models.IntegerField(null=True)
    Pascucci=models.IntegerField(null=True)

class Brand(models.Model):
    id=models.IntegerField(primary_key=True)
    brand=models.CharField(max_length=15)

class Location(models.Model):
    id = models.IntegerField(primary_key=True)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    store=models.CharField(max_length=30)
    location=models.CharField(max_length=50)
    lat=models.FloatField(null=True)
    lng=models.FloatField(null=True)

class Post(models.Model):
    writer=models.ForeignKey(Users,on_delete=models.CASCADE)
    title=models.TextField()
    content=models.TextField()
    writedate=models.DateTimeField(auto_now_add=True)
    cnt=models.IntegerField(default=0)
    like=models.IntegerField(default=0)

    @property
    def update_counter(self):
        self.cnt+=1
        self.save()

    @property
    def up_like(self):
        self.like+=1
        self.save()

    @property
    def down_like(self):
        self.like-=1
        self.save()

class recommend(models.Model):
    useremail=models.ForeignKey(Users,on_delete=models.CASCADE)
    post=models.ForeignKey(Post,on_delete=models.CASCADE)

project/mainapp/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect


# Create your views here.
from mainapp.models import Product, Price_Bybrand, Product_Bybrand
from mainapp.models import Brand,Location
from mainapp.models import Post,recommend
from django.core.paginator import Paginator
from usersapp.models import Users

enToko={ "Americano":"아메리카노",
         "Coffee Latte":"카페라떼",
         "Cappuccino":"카푸치노",
         "Vanilla Latte":"바닐라라떼",
         "Cafe Mocha":"카페모카",
         "Caramel Macchiato":"카라멜마끼아또",
         "Cold Brew":"콜드브루",
         "Green Tea Latte":"그린티라떼",
         "Chocolate Latte":"초콜릿라떼",
         "Starbucks":"스타벅스",
         "Twosome":"투썸플레이스",
         "TomandToms":"탐앤탐스",
         "Ediya":"이디야",
         "Mega":"메가커피",
         "Hollys":"할리스",
         "Coffeebean":"커피빈",
         "Coffeebay":"커피베이",
         "Angelinus":"엔제리너스",
         "Pascucci":"파스쿠찌"}

adv={"Ediyaevent":'https://www.ediya.com/contents/event.html?tb_name=event&bbs_section=view&Ctg=&page=1&idx=122',
     "Pascuccievent":"http://www.caffe-pascucci.co.kr/event/eventView.asp?teSeq=433",
<<<<<<< HEAD
     "Tomntomsevent":"https://www.tomntoms.com/event/eventView.php?vIDX=562&",
=======
     "Tomntomsevent":"https://www.tomntoms.com/event/event.html?bmain=view&uid=7&mode=",
>>>>>>> 879670d8dbe977902ecac6468182fc1505a136fa
     "Hollysevent":"https://www.hollys.co.kr/news/event/view.do?idx=230&pageNo=1&division="}



def home(request):
    context={}
    comments={"Americano":"아메리카노의 쓴맛을 즐기는 것, 어른이 됐다는 것.",
             "Coffee Latte":"라떼는 말야, 라떼를 마셨어.",
             "Cappuccino":"부드러운 거품, 고소한 시나몬, 인생은 카푸치노처럼.",
             "Vanilla Latte":"당 떨어지는 오후3시, 바닐라라떼.",
             "Cafe Mocha":"일상에 초콜릿 한 스푼, 카페모카.",
             "Caramel Macchiato":"마끼아또, 마셔봐또?",
             "Cold Brew":"시간을 마시다, 콜드브루.",
             "Green Tea Latte":"그린티라떼가 녹차라떼고, 녹차라떼가 그린티라떼야.",
             "Chocolate Latte":"어리다고 놀리지 말아요. 달달한 초콜릿라떼."}

    context["adv"]=adv
    context["comments"]=comments
    if 'user' in request.session:
        context['user_name']=request.session.get('user')
        return render(request,'home.html',context)
    else:
        return render(request,'home.html',context)

def logout(request):
    if 'user' in request.session:
        del request.session['email']
        del request.session['user']

        if request.GET['next'] == "/mainapp/mypage/":
            return redirect("/mainapp/home/")
        else:
            return redirect(request.GET['next'])

def best9(request):
    context={}
    context["product"]=request.GET['product']
    ## global enToko
    ko_name=enToko[request.GET['product']]
    product=Product.objects.filter(products=ko_name)
    price=Price_Bybrand.objects.get(pk=product[0].id)
    name=Product_Bybrand.objects.get(pk=product[0].id)
    coffee_list={}
    for i,(brand,coffee,cost) in enumerate(zip(price.__dict__,name.__dict__.values(),price.__dict__.values())):
        if i>=2 and coffee != None:
            coffee_list[brand]=str(coffee)+"/"+str(cost)+"원"
    context["coffee_list"]=coffee_list
    print(coffee_list)

    if 'user' in request.session:
        context['user_name']=request.session.get('user')

    return render(request,'bestmenu.html',context)

def cafemap(request):
    context={}
    # 영문 이름 받기
    context['store']=request.GET['store']
    store=enToko[request.GET['store']]
    brand=Brand.objects.filter(brand=store)
    location=Location.objects.filter(brand_id=brand[0].id)
    context['Location']=location

    if 'user' in request.session:
        context['user_name']=request.session.get('user')
    return render(request,'cafemap.html',context)

def brandmenu(request):
    context={}
    menu_list=["Starbucks","TwosomePlace","TomnToms","Ediya","MegaCoffee","Hollys",
               "CoffeeBean","CoffeeBay","Angelinus","Pascucci"]
    context['menu_list']=menu_list

    if 'user' in request.session:
        context['user_name']=request.session.get('user')
    return render(request,'brandmenu.html',context)

def post(request):
    context={}
    if 'user' in request.session:
        context['user_name']=request.session.get('user')
    if 'error' in request.session:
        context['error']=request.session.get('error')
        del request.session['error']

    if request.method == "POST":
        title=request.POST['title']
        content=request.POST['content']
        if 'user' in request.session:
            writer=request.session['email']
            post=Post(writer_id=writer,title=title,content=content)
            post.save()
            return redirect('post')
        else:
            return redirect('/mainapp/post/?err='+"먼저 로그인을 해주세요.")
    else:
        page = int(request.GET.get('page', 1))
        post=Post.objects.all()
        post=post.order_by('-writedate')
        paginator = Paginator(post, 10)
        pagelist = paginator.get_page(page)
        position = page - 1
        # visible_page: Pagination에 보여질 개수
        visible_page = 5
        R = position // visible_page
        visible_list = []
        for i in range((R * visible_page) + 1, ((R + 1) * visible_page) + 1):
            if i > paginator.num_pages: break
            visible_list.append(i)

        context["Post"]=pagelist
        context['total']=visible_list
        context['current']=page
        return render(request,'post.html',context)

def write(request):
    context={}
    id=request.GET.get('id',None)

    if id:
        if 'user' in request.session:
            context['user_name']=request.session.get('user')
        view=Post.objects.get(id=id)
        context["view"]=view
        return render(request,'write.html',context)
    else:
        if 'user' in request.session:
            context['user_name']=request.session.get('user')
            return render(request,'write.html',context)
        else:
            request.session['error']="먼저 로그인을 해주세요."
            return redirect("/mainapp/post/")

def view(request):
    context={}
    id = request.GET['view']

    context['update']=request.GET.get('update',None)

    if 'error' in request.session:
        context['error'] = request.session.get('error')
        del request.session['error']

    if 'user' in request.session:
        context['user_name']=request.session.get('user')
        context['user_email']=request.session.get('email')
        try:
            like=recommend.objects.filter(useremail_id=request.session.get('email'))
        except recommend.DoesNotExist:
            pass
        else:
            if int(id) in list(map(lambda x:x.post_id,like)):
                context['islike']=True
            else:
                context['islike']=False

    view=Post.objects.get(pk=id)
    context['view']=view
    return render(request,'view.html',context)

def notlike(request):
    post_id=request.GET['post_id']
    user_id=request.GET['user_id']

    if 'user' not in request.session:
        jsonContent={"error":"먼저 로그인을 해주세요."}
        return JsonResponse(jsonContent, json_dumps_params={'ensure_ascii': False})



    view = Post.objects.get(pk=post_id)
    view.up_like
    recom=recommend(post_id=post_id,useremail_id=user_id)
    recom.save()
    return JsonResponse({}, json_dumps_params={'ensure_ascii':False})

def islike(request):
    post_id = request.GET['post_id']
    user_id = request.GET['user_id']
    view=Post.objects.get(pk=post_id)
    view.down_like
    recom=recommend.objects.filter(post_id=post_id,useremail_id=user_id)
    recom.delete()
    return JsonResponse({}, json_dumps_params={'ensure_ascii':False})

def update_cnt(request):
    post_id=request.GET['id']
    loc=request.GET['loc']
    view=Post.objects.get(pk=post_id)
    view.update_counter
    return redirect(loc)

def mypage(request):
    context={}

    if 'user' in request.session:
        context['user_name']=request.session['user']
        context['user_email']=request.session['email']
        email=request.session['email']
        user_post = Post.objects.filter(writer_id=email)
        user_post=user_post.order_by('-writedate')
        context['Post']=user_post

    return render(request,'mypage.html',context)

def userpost(request):
    email=request.GET['email']
    user_post=Post.objects.filter(writer_id=email)
    jsonContent={"Post":user_post}
    return JsonResponse(jsonContent,json_dumps_params={'ensure_ascii':False})

def remove(request):
    id=request.GET['id']
    view=Post.objects.get(id=id)
    view.delete()
    return redirect("/mainapp/mypage/")

def update(request):
    id=request.GET.get('id')
    view=Post.objects.get(id=id)
    view.title=request.POST['title']
    view.content=request.POST['content']
    view.save()
    return redirect("/mainapp/mypage/")

project/mainapp/templates/bestmenu.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Coffee</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
        <!--CSS============================================= -->
        <link rel="stylesheet" href="/static/css/linearicons.css">
        <link rel="stylesheet" href="/static/css/font-awesome.min.css">
        <link rel="stylesheet" href="/static/css/bootstrap.css">
        <link rel="stylesheet" href="/static/css/magnific-popup.css">
        <link rel="stylesheet" href="/static/css/nice-select.css">
        <link rel="stylesheet" href="/static/css/animate.min.css">
        <link rel="stylesheet" href="/static/css/owl.carousel.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
        <style>
            .body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
            .w3-bar-block .w3-bar-item {padding:20px}

            .git:hover{
                    opacity:0.5;
                }
        </style>
</head>

<body>
          <header id="header" id="home" style="background-color:#423433; ">
            <div class="container">
                <div class="row align-items-center justify-content-between d-flex">
                  <div id="logo">
                    <a href="{% url 'home' %}">
                        <img src="/static/img/logo-new.png" style="width:40px; float:left;" alt="" title="" />
                        <h1 style="color:white; float:left; margin-left:20px; font-family: 'Poppins', sans-serif;">Cafe Olleh?</h1>
                    </a>
                  </div>
                  <nav id="nav-menu-container">
                    <ul class="nav-menu">
                      <li class="menu-active" style="font-family: 'Poppins', sans-serif;"><a href="{% url 'home' %}">Home</a></li>
                      <li><a href="{% url 'home'%}#event" style="font-family: 'Poppins', sans-serif;">Event</a></li>
                      <li><a href="{% url 'home'%}#best9" style="font-family: 'Poppins', sans-serif;">Best 9</a></li>
                      <li><a href="{% url 'brandmenu'%}" style="font-family: 'Poppins', sans-serif;">Menu</a></li>
                      <li><a href="{% url 'post'%}" style="font-family: 'Poppins', sans-serif;">Support</a></li>
                      {% if user_name %}
                        <li><a href="#" onclick="return false;">{{user_name}} 님!</a>
                            <ul>
                              <li><a href="{% url 'mypage' %}" style="font-family: 'Poppins', sans-serif;">내 정보</a></li>
                              <li><a href="{% url 'logout'%}?next={{request.get_full_path}}" style="font-family: 'Poppins', sans-serif;">Log Out!!</a></li>
                            </ul>
                        </li>
                      {% else %}
                        <li><a href="{% url 'usersapp:login'%}?next={{request.get_full_path}}" style="font-family: 'Poppins', sans-serif;">Log in</a></li>
                      {% endif %}

                    </ul>
                  </nav><!-- #nav-menu-container -->
                </div>
            </div>
          </header><!-- #header -->

      <div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">
        <h2>{{product}}</h2><hr style="border:1px solid black;"><!--{{아메리카노}}-->
        <!-- First Photo Grid-->
        <div class="w3-row-padding w3-padding-16 w3-center"  id="food">
            {% for key,value in coffee_list.items%}
                <div class="w3-quarter" style="margin-top:25px;">
                    <img src="/static/img/{{key}}.jpg" alt="Steak" style="width:100px; height:100px;">
                    <h3>{{key}}</h3>
                    <p>{{value}}</p>
                    <a href="{% url 'cafemap'%}?store={{key}}" class="primary-btn text-uppercase" style="background-color:#423433; color:white;">근처 매장 보기</a>
                </div>
            {%endfor%}
        </div>
      </div>

        <!-- start footer Area -->
		<footer class="footer-area section-gap">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h6>About Us</h6>

							<a href="https://github.com/N-analyst" target="_blank"><img class="git" src="/static/img/git.png" style="width:50px;"></a>
								N-analyst<br><br>
							<a href="https://github.com/Lia-97" target="_blank"><img class="git" src="/static/img/git.png" style="width:50px;"></a>
								Lia-97<br><br>
							<a href="https://github.com/Hsquare-get" target="_blank"><img class="git" src="/static/img/git.png" style="width:50px;"></a>
								Hsquare-get <br><br>


						</div>
					</div>
					<div class="col-lg-5  col-md-6 col-sm-6" style="position:relative; right:100px;">
						<div class="single-footer-widget">
							<h6>Story</h6>
							<p>우리는 파편적인 카페정보에 불편함을 느껴 해당 프로젝트 시작하였습니다. 더 많은 이야기가 궁금하면 아이콘을 클릭해 주세요.</p>
							<p class="footer-text">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</p>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-6 social-widget">
						<div class="single-footer-widget">
							<h6>Follow Us</h6>
							<p>Let us be social</p>
							<div class="footer-social d-flex align-items-center">
								<a href="https://www.instagram.com/cafe__olleh/?hl=ko" target="_blank"><i class="fa fa-instagram"></i></a>
								<a href="https://github.com/N-analyst/Cafe_Olleh" target="_blank"><i class="fa fa-github"></i></a>
								<a href="#"><i class="fa fa-dribbble" target="_blank"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- End footer Area -->

        <script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="/static/js/vendor/bootstrap.min.js"></script>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
        <script src="/static/js/easing.min.js"></script>
        <script src="/static/js/hoverIntent.js"></script>
        <script src="/static/js/superfish.min.js"></script>
        <script src="/static/js/jquery.ajaxchimp.min.js"></script>
        <script src="/static/js/jquery.magnific-popup.min.js"></script>
        <script src="/static/js/owl.carousel.min.js"></script>
        <script src="/static/js/jquery.sticky.js"></script>
        <script src="/static/js/jquery.nice-select.min.js"></script>
        <script src="/static/js/parallax.min.js"></script>
        <script src="/static/js/waypoints.min.js"></script>
        <script src="/static/js/jquery.counterup.min.js"></script>
        <script src="/static/js/mail-script.js"></script>
        <script src="/static/js/main.js"></script>
</body>
</html>

project/mainapp/templates/brandmenu.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Coffee</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
        <!--CSS============================================= -->
        <link rel="stylesheet" href="/static/css/linearicons.css">
        <link rel="stylesheet" href="/static/css/font-awesome.min.css">
        <link rel="stylesheet" href="/static/css/bootstrap.css">
        <link rel="stylesheet" href="/static/css/magnific-popup.css">
        <link rel="stylesheet" href="/static/css/nice-select.css">
        <link rel="stylesheet" href="/static/css/animate.min.css">
        <link rel="stylesheet" href="/static/css/owl.carousel.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
        <!--W3C CSS-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <style>
        .body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
        .w3-bar-block .w3-bar-item {padding:20px}




        ul.nav-pills {
            top: 20px;
            position: fixed;
        }

        ul.nav-tabs {
            top: 20px;
            position: fixed;
        }

        #brand_menu{
            position: relative;
        }

        </style>
</head>

<body id="brand_menu" data-spy="scroll" data-target="#myScrollspy" data-offset="1">
          <header id="header" id="home" style="background-color:#423433; ">
            <div class="container">
                <div class="row align-items-center justify-content-between d-flex">
                  <div id="logo">
                    <a href="{% url 'home' %}">
                        <img src="/static/img/logo-new.png" style="width:40px; float:left;" alt="" title="" />
                        <h1 style="color:white; float:left; margin-left:20px; font-family: 'Poppins', sans-serif;">Cafe Olleh?</h1>
                    </a>
                  </div>
                  <nav id="nav-menu-container">
                    <ul class="nav-menu">
                      <li class="menu-active" style="font-family: 'Poppins', sans-serif;"><a href="{% url 'home' %}" style="color:white; text-decoration:none;">Home</a></li>
                      <li><a href="{% url 'home'%}#event" style="font-family: 'Poppins', sans-serif; color:white; text-decoration:none;">Event</a></li>
                      <li><a href="{% url 'home'%}#best9" style="font-family: 'Poppins', sans-serif; color:white; text-decoration:none;">Best 9</a></li>
                      <li><a href="{% url 'brandmenu' %}" style="font-family: 'Poppins', sans-serif; color:white; text-decoration:none;">Menu</a></li>
                      <li><a href="{% url 'post'%}" style="font-family: 'Poppins', sans-serif; color:white; text-decoration:none;">Support</a></li>
                      {% if user_name %}
                        <li><a href="#" onclick="return false;" style="color:white; text-decoration:none;">{{user_name}} 님!</a>
                            <ul>
                              <li><a href="{% url 'mypage' %}" style="font-family: 'Poppins', sans-serif;">내 정보</a></li>
                              <li><a href="{% url 'logout'%}?next={{request.get_full_path}}" style="font-family: 'Poppins', sans-serif;">Log Out!!</a></li>
                            </ul>
                        </li>
                      {% else %}
                        <li><a href="{% url 'usersapp:login'%}?next={{request.get_full_path}}" style="font-family: 'Poppins', sans-serif; color:white; text-decoration:none;">Log in</a></li>
                      {% endif %}

                    </ul>
                  </nav><!-- #nav-menu-container -->
                </div>
            </div>
          </header><!-- #header -->

      <div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px" >
        <h2>Brand Menu</h2><hr style="border:1px solid black;"><!--{{아메리카노}}-->
        <!-- First Photo Grid-->
        <div>
            <div class="container-fluid">
              <div class="row">
                <nav class="col-sm-3 col-4" id="myScrollspy" >
                  <ul class="nav nav-pills flex-column" style="margin-top:150px;">
                    {% for brand in menu_list%}
                      <li class="nav-item">
                        <a class="nav-link" href="#{{brand}}">{{brand}}</a>
                      </li>
                    {% endfor%}
                  </ul>
                </nav>
                <div class="col-sm-9 col-8">
                    {% for brand in menu_list%}
                        <div id="{{brand}}" class="w3-main w3-content w3-padding" style="max-width:1200px; margin-top:25px">
                          <h2  style="margin-top:100px">{{brand}}</h2><hr style="border:1px solid black;"><!--{{아메리카노}}-->
                          <div  class="bg-warning" style="margin-top:50px; margin-bottom:50px;" >
<<<<<<< HEAD
                               <img src="/static/img/{{brand}}_menu.jpg" style="width:100%;">
=======
                                <img src="/static/img/{{brand}}_menu.jpg" style="width:100%;">
>>>>>>> 919d08f8da838034fa7df2d332dfce36d409e8b3
                          </div>
                        </div>
                    {% endfor %}
                </div>
              </div>
            </div>
        </div>
      </div>

        <script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="/static/js/vendor/bootstrap.min.js"></script>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
        <script src="/static/js/easing.min.js"></script>
        <script src="/static/js/hoverIntent.js"></script>
        <script src="/static/js/superfish.min.js"></script>
        <script src="/static/js/jquery.ajaxchimp.min.js"></script>
        <script src="/static/js/jquery.magnific-popup.min.js"></script>
        <script src="/static/js/owl.carousel.min.js"></script>
        <script src="/static/js/jquery.sticky.js"></script>
        <script src="/static/js/jquery.nice-select.min.js"></script>
        <script src="/static/js/parallax.min.js"></script>
        <script src="/static/js/waypoints.min.js"></script>
        <script src="/static/js/jquery.counterup.min.js"></script>
        <script src="/static/js/mail-script.js"></script>
        <script src="/static/js/main.js"></script>
</body>
</html>